[build]
filehash = false              # If you set it to false the rebuild doesn't make page reload the new files
public_url = "/tauri_gardesh"
no-sri = true
release = false

[watch]
ignore = ["./src-tauri"]

[serve]
addresses = ["0.0.0.0"]
port = 1420
open = false
ws_protocol = "ws"
