[build]
filehash = true          # If you set it to false the rebuild doesn't make page reload the new files
no-sri = true
port = 1420
# [build]
# target = "./index.html"
# filehash = false
# no-sri=true

[watch]
ignore = ["./src-tauri"]

[serve]
filehash = true          # If you set it to false the rebuild doesn't make page reload the new files
no-sri = true
port = 1420
open = false
ws_protocol = "ws"
address = "0.0.0.0"

# no-sri=true
